[project]
name = "casasoft-auth"
version = "0.1.0"
description = "Cliente de autenticaÃ§Ã£o Casasoft / CloudSlim"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.28"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"